---
spring.profiles: local, dev

hostname: localhost

# PORT NUMBERS #
discovery.service.port: 8081
gateway.service.port: 8082
webapp.port: 8099

---
spring.profiles: local, dev, prod

# ENDPOINTS #
gateway.endpoint: http://${hostname}:${gateway.service.port}

eureka:
  instance:
    hostname: ${hostname}
    instanceId: ${hostname}:${server.port}-${spring.application.name}-${random.value}
  client:
    serviceUrl:
      defaultZone: http://${hostname}:${discovery.service.port}/eureka/