---
spring.profiles: local, dev
discovery.service.port: 8081
gateway.service.port: 8082
user.service.port: 0

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:${discovery.service.port}/eureka/

---
spring.profiles: prod
eureka:
  instance:
    hostname: ${hostname}
  client:
    serviceUrl:
      defaultZone: http://${hostname}:${discovery.service.port}/eureka/