---
spring.profiles: local, dev

hostname: localhost

# PORT NUMBERS #
discovery.service.port: 8081
gateway.service.port: 8082
user.service.port: 0
aperture.webapp.port: 8099


---
spring.profiles: local, dev, prod

# ENDPOINTS #
gateway.endpoint: http://${hostname}:${gateway.service.port}

eureka:
  instance:
    hostname: ${hostname}
  client:
    serviceUrl:
      defaultZone: http://${hostname}:${discovery.service.port}/eureka/