server:
  port: ${gateway.service.port}

eureka:
  instance:
    instanceId: ${eureka.instance.hostname}:${server.port}/${app.name}
  client:
    registerWithEureka: true
    fetchRegistry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**