server:
  port: ${gateway.service.port}

eureka:
  instance:
    instanceId: ${eureka.instance.hostname}:${server.port}-${spring.application.name}-${random.value}
  client:
    registerWithEureka: false
    fetchRegistry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user
        uri: lb://user-api
        predicates:
        - Path=/user-api/**