server:
  port: ${gateway.service.port}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user
        uri: lb://user-api
        predicates:
        - Path=/user-api/**